---
title: "Bio"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Pronouns: she/her

### Bio

Juliet is a conservation biologist interested in the interaction between urban landscapes and wildlife population dynamics in the face of climate change. She is pursuing a Master’s degree in Environmental Data Science from UC Santa Barbara’s Bren School of Environmental Science and Management. Prior to the Bren School, she earned a Bachelor’s degree in Ecology and Evolution with distinction in the major from UC Santa Barbara in 2019 and studied abroad in Costa Rica. Juliet’s undergraduate research investigated mammalian spatial ecology throughout local urban communities. Following this research, she served as a field technician studying endangered populations of flat-tailed horned lizards and steelhead trout in Southern California. With a growing interest in dynamic urban ecosystems, she went on to study incipient invasive species across the Hawaiian islands. These projects inspired Juliet to delve into environmental data science in order to recognize broad ecological patterns across diverse scientific disciplines. Going forward, she aims to utilize modelling techniques and spatial data science to understand the population dynamics of species that are most imperiled by urban expansion and climate change. With open source programming tools and a collaborative approach, she hopes to advise preventative policies to protect wildlife from anthropogenic influence.
